package familymanagersystem.forms;

import javax.swing.JOptionPane;

/**
 *
 * @author Dário Silva & Délcio Morais
 * @since 2023
 * @version 1.0
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    //variables used to move to screen
    int xMouse;
    int yMouse;

    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackground = new javax.swing.JPanel();
        jAdminLogo = new javax.swing.JLabel();
        jUsernameFieldLabel = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        jPasswordFieldLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(19, 19, 19));
        setLocation(new java.awt.Point(415, 100));
        setName("Admin: Login"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBackground.setBackground(new java.awt.Color(19, 19, 19));
        jBackground.setBorder(javax.swing.BorderFactory.createMatteBorder(-1, -1, -1, -1, new java.awt.Color(110, 86, 219)));

        jAdminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_logo.png"))); // NOI18N

        jUsernameFieldLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jUsernameFieldLabel.setForeground(new java.awt.Color(110, 86, 219));
        jUsernameFieldLabel.setText("Name");

        jUsernameField.setBackground(new java.awt.Color(22, 22, 22));
        jUsernameField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jUsernameField.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jUsernameField.setToolTipText("Introduce the name");
        jUsernameField.setAutoscrolls(false);
        jUsernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(37, 37, 37)));
        jUsernameField.setCaretColor(new java.awt.Color(102, 102, 102));
        jUsernameField.setMargin(new java.awt.Insets(2, 5, 2, 2));

        jPasswordFieldLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jPasswordFieldLabel.setForeground(new java.awt.Color(110, 86, 219));
        jPasswordFieldLabel.setText("Password");

        jPasswordField.setBackground(new java.awt.Color(22, 22, 22));
        jPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(37, 37, 37)));

        jButton1.setBackground(new java.awt.Color(42, 42, 42));
        jButton1.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Complete Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_icon.png"))); // NOI18N
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jBackgroundLayout = new javax.swing.GroupLayout(jBackground);
        jBackground.setLayout(jBackgroundLayout);
        jBackgroundLayout.setHorizontalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackgroundLayout.createSequentialGroup()
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBackgroundLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jUsernameFieldLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldLabel)
                            .addComponent(jUsernameField)
                            .addComponent(jPasswordField)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBackgroundLayout.createSequentialGroup()
                .addGap(0, 200, Short.MAX_VALUE)
                .addComponent(jAdminLogo)
                .addGap(160, 160, 160)
                .addComponent(jClose)
                .addGap(28, 28, 28))
        );
        jBackgroundLayout.setVerticalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackgroundLayout.createSequentialGroup()
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBackgroundLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jClose))
                    .addGroup(jBackgroundLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jAdminLogo)))
                .addGap(40, 40, 40)
                .addComponent(jUsernameFieldLabel)
                .addGap(18, 18, 18)
                .addComponent(jUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPasswordFieldLabel)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 490));

        getAccessibleContext().setAccessibleName("Admin Area Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // log into the admin account
        String username = jUsernameField.getText();
        char[] password = jPasswordField.getPassword();

        //tests if both field are empty
        if (username.isBlank() && password.length == 0) {
            JOptionPane.showMessageDialog(null, "You Need To Fill All The Fields", "Please, Fill Out All Fields", 0);
        } else {
            //tests if a field is empty
            if (username.isBlank() || password.length == 0) {
                JOptionPane.showMessageDialog(null, "You Need To Fill All The Fields", "Please, Fill Out All Fields", 0);
            } else {
                /**
                 * we know that this isn't secure but for now we gonna let it
                 * this way
                 */

                if (username.equalsIgnoreCase("Dário Silva") || username.equalsIgnoreCase("Dario Silva") && password.equals("108449")) {
                    //closes the current window
                    dispose();
                    
                    //opens the system dahsboard
                    new SystemDashBoard().setVisible(true);
                } else if (username.equalsIgnoreCase("Délcio Morais") || username.equalsIgnoreCase("Delcio Morais") && password.equals("390519")) {
                    //closes the current window
                    dispose();

                    //opens the system dahsboard
                    new SystemDashBoard().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "This Admin doesn't exists", "Error 404: Admin Not Found", 2);
                    jUsernameField.setText("");
                    jPasswordField.setText("");
                }

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // allows the user to moviment the form when dragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // gets the X and Y from the Screen
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // closes the system
        System.exit(0);
    }//GEN-LAST:event_jCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAdminLogo;
    private javax.swing.JPanel jBackground;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jClose;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel jPasswordFieldLabel;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JLabel jUsernameFieldLabel;
    // End of variables declaration//GEN-END:variables
}
