package familymanagersystem.forms;

import java.io.IOException;

/**
 *
 * @author Dário Silva & Délcio Morais
 * @since 2023
 * @version 1.0
 */
public class DashboardHomeScreen extends javax.swing.JPanel {

    /**
     * Creates new form DashboardHomeScreen
     */
    public DashboardHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCloseBtn = new javax.swing.JLabel();
        jcompaniesPanel = new javax.swing.JPanel();
        jbusinessIcon = new javax.swing.JLabel();
        jBusinessTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jamountPanel = new javax.swing.JPanel();
        jmoneyIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTotalAmount = new javax.swing.JLabel();
        jfamiliesPanel = new javax.swing.JPanel();
        jfamilyIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jNumberOfFamilies = new javax.swing.JLabel();
        jfamiliesPanel1 = new javax.swing.JPanel();
        jdashboardHomeScreenBackground = new javax.swing.JPanel();

        setBackground(new java.awt.Color(19, 19, 19));
        setPreferredSize(new java.awt.Dimension(766, 437));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 32, -1, -1));

        jCloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_dark.png"))); // NOI18N
        jCloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseBtnMouseClicked(evt);
            }
        });
        add(jCloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 11, -1, -1));

        jcompaniesPanel.setBackground(new java.awt.Color(45, 45, 45));
        jcompaniesPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(232, 225, 68)));
        jcompaniesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcompaniesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcompaniesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcompaniesPanelMouseExited(evt);
            }
        });

        jbusinessIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/business_icon.png"))); // NOI18N

        jBusinessTitle.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jBusinessTitle.setForeground(new java.awt.Color(255, 255, 255));
        jBusinessTitle.setText("Business");

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" 0");

        javax.swing.GroupLayout jcompaniesPanelLayout = new javax.swing.GroupLayout(jcompaniesPanel);
        jcompaniesPanel.setLayout(jcompaniesPanelLayout);
        jcompaniesPanelLayout.setHorizontalGroup(
            jcompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcompaniesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbusinessIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBusinessTitle)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcompaniesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jcompaniesPanelLayout.setVerticalGroup(
            jcompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcompaniesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbusinessIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBusinessTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        add(jcompaniesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 52, -1, -1));

        jamountPanel.setBackground(new java.awt.Color(45, 45, 45));
        jamountPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(64, 226, 119)));
        jamountPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jamountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jamountPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jamountPanelMouseExited(evt);
            }
        });

        jmoneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cash_icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Amount");

        jTotalAmount.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jTotalAmount.setForeground(new java.awt.Color(255, 255, 255));
        jTotalAmount.setText(" 0 kzs");

        javax.swing.GroupLayout jamountPanelLayout = new javax.swing.GroupLayout(jamountPanel);
        jamountPanel.setLayout(jamountPanelLayout);
        jamountPanelLayout.setHorizontalGroup(
            jamountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jmoneyIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jamountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jamountPanelLayout.setVerticalGroup(
            jamountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jamountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmoneyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jTotalAmount)
                .addGap(20, 20, 20))
        );

        add(jamountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 52, -1, -1));

        jfamiliesPanel.setBackground(new java.awt.Color(45, 45, 45));
        jfamiliesPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(110, 86, 219)));
        jfamiliesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jfamiliesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jfamiliesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jfamiliesPanelMouseExited(evt);
            }
        });

        jfamilyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/family_medium_icon.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Families");

        jNumberOfFamilies.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jNumberOfFamilies.setForeground(new java.awt.Color(255, 255, 255));
        try{
            jNumberOfFamilies.setText(RegistrationMainScreenInfoFields.getsTheNumberOfFamilies());
        }catch(IOException e){
            System.out.println("Error:"+e.getMessage()+" - Error1: "+e.getCause());
        }

        javax.swing.GroupLayout jfamiliesPanelLayout = new javax.swing.GroupLayout(jfamiliesPanel);
        jfamiliesPanel.setLayout(jfamiliesPanelLayout);
        jfamiliesPanelLayout.setHorizontalGroup(
            jfamiliesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfamiliesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfamilyIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfamiliesPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jNumberOfFamilies)
                .addGap(44, 44, 44))
        );
        jfamiliesPanelLayout.setVerticalGroup(
            jfamiliesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfamiliesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfamiliesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jfamilyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jNumberOfFamilies)
                .addGap(19, 19, 19))
        );

        add(jfamiliesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 52, 233, -1));

        jfamiliesPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jfamiliesPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(85, 171, 219)));
        jfamiliesPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jfamiliesPanel1Layout = new javax.swing.GroupLayout(jfamiliesPanel1);
        jfamiliesPanel1.setLayout(jfamiliesPanel1Layout);
        jfamiliesPanel1Layout.setHorizontalGroup(
            jfamiliesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jfamiliesPanel1Layout.setVerticalGroup(
            jfamiliesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        add(jfamiliesPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 186, -1, -1));

        jdashboardHomeScreenBackground.setBackground(new java.awt.Color(19, 19, 19));

        javax.swing.GroupLayout jdashboardHomeScreenBackgroundLayout = new javax.swing.GroupLayout(jdashboardHomeScreenBackground);
        jdashboardHomeScreenBackground.setLayout(jdashboardHomeScreenBackgroundLayout);
        jdashboardHomeScreenBackgroundLayout.setHorizontalGroup(
            jdashboardHomeScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jdashboardHomeScreenBackgroundLayout.setVerticalGroup(
            jdashboardHomeScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        add(jdashboardHomeScreenBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void jCloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseBtnMouseClicked
        // exits the system
        System.exit(0);
    }//GEN-LAST:event_jCloseBtnMouseClicked

    private void jamountPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jamountPanelMouseEntered
        // changes the background color
        jamountPanel.setBackground(new java.awt.Color(47, 47, 47));
    }//GEN-LAST:event_jamountPanelMouseEntered

    private void jfamiliesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfamiliesPanelMouseEntered
        // changes the background color
        jfamiliesPanel.setBackground(new java.awt.Color(47, 47, 47));
    }//GEN-LAST:event_jfamiliesPanelMouseEntered

    private void jfamiliesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfamiliesPanelMouseExited
        // changes the background color
        jfamiliesPanel.setBackground(new java.awt.Color(45, 45, 45));
    }//GEN-LAST:event_jfamiliesPanelMouseExited

    private void jamountPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jamountPanelMouseExited
        // changes the background color
        jfamiliesPanel.setBackground(new java.awt.Color(45, 45, 45));
    }//GEN-LAST:event_jamountPanelMouseExited

    private void jcompaniesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcompaniesPanelMouseEntered
        // changes the background color
        jcompaniesPanel.setBackground(new java.awt.Color(47, 47, 47));
    }//GEN-LAST:event_jcompaniesPanelMouseEntered

    private void jcompaniesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcompaniesPanelMouseExited
        // changes the background color
        jcompaniesPanel.setBackground(new java.awt.Color(45, 45, 45));
    }//GEN-LAST:event_jcompaniesPanelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBusinessTitle;
    private javax.swing.JLabel jCloseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNumberOfFamilies;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTotalAmount;
    private javax.swing.JPanel jamountPanel;
    private javax.swing.JLabel jbusinessIcon;
    private javax.swing.JPanel jcompaniesPanel;
    private javax.swing.JPanel jdashboardHomeScreenBackground;
    private javax.swing.JPanel jfamiliesPanel;
    private javax.swing.JPanel jfamiliesPanel1;
    private javax.swing.JLabel jfamilyIcon;
    private javax.swing.JLabel jmoneyIcon;
    // End of variables declaration//GEN-END:variables
}
