package familymanagersystem.forms;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Dário Silva & Délcio Morais
 * @since 2023
 * @version 1.0
 */
public class DashboardFamilyOptionsScreen extends javax.swing.JPanel {

    /**
     * Creates new form DashboardFamilyOptionsScreen
     */
    public DashboardFamilyOptionsScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jnewFamilyPanel = new javax.swing.JPanel();
        jaddIcon = new javax.swing.JLabel();
        jAddFamilyTitle = new javax.swing.JLabel();
        jAddFamily = new javax.swing.JLabel();
        jfamilyOptionsScreenBackground = new javax.swing.JPanel();

        setBackground(new java.awt.Color(19, 19, 19));
        setPreferredSize(new java.awt.Dimension(766, 437));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(45, 45, 45));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jnewFamilyPanel.setBackground(new java.awt.Color(45, 45, 45));
        jnewFamilyPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(164, 68, 232)));
        jnewFamilyPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jnewFamilyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jnewFamilyPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jnewFamilyPanelMouseExited(evt);
            }
        });

        jaddIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_medium_icon.png"))); // NOI18N

        jAddFamilyTitle.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jAddFamilyTitle.setForeground(new java.awt.Color(255, 255, 255));
        jAddFamilyTitle.setText("Add new family");

        jAddFamily.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jAddFamily.setForeground(new java.awt.Color(255, 255, 255));
        jAddFamily.setText("Register now");
        jAddFamily.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAddFamily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddFamilyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jnewFamilyPanelLayout = new javax.swing.GroupLayout(jnewFamilyPanel);
        jnewFamilyPanel.setLayout(jnewFamilyPanelLayout);
        jnewFamilyPanelLayout.setHorizontalGroup(
            jnewFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jnewFamilyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jaddIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAddFamilyTitle)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jnewFamilyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAddFamily)
                .addGap(23, 23, 23))
        );
        jnewFamilyPanelLayout.setVerticalGroup(
            jnewFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jnewFamilyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jnewFamilyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jaddIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAddFamilyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jAddFamily)
                .addGap(21, 21, 21))
        );

        add(jnewFamilyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jfamilyOptionsScreenBackground.setBackground(new java.awt.Color(19, 19, 19));

        javax.swing.GroupLayout jfamilyOptionsScreenBackgroundLayout = new javax.swing.GroupLayout(jfamilyOptionsScreenBackground);
        jfamilyOptionsScreenBackground.setLayout(jfamilyOptionsScreenBackgroundLayout);
        jfamilyOptionsScreenBackgroundLayout.setHorizontalGroup(
            jfamilyOptionsScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jfamilyOptionsScreenBackgroundLayout.setVerticalGroup(
            jfamilyOptionsScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        add(jfamilyOptionsScreenBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jnewFamilyPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnewFamilyPanelMouseExited
        // changes the background color
        jnewFamilyPanel.setBackground(new java.awt.Color(45, 45, 45));
    }//GEN-LAST:event_jnewFamilyPanelMouseExited

    private void jnewFamilyPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnewFamilyPanelMouseEntered
        // changes the background color
        jnewFamilyPanel.setBackground(new java.awt.Color(47, 47, 47));
    }//GEN-LAST:event_jnewFamilyPanelMouseEntered

    private void jAddFamilyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddFamilyMouseClicked
        // opens the registrationMainScreen form
        new RegistrationMainScreen().setVisible(true);
    }//GEN-LAST:event_jAddFamilyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddFamily;
    private javax.swing.JLabel jAddFamilyTitle;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jaddIcon;
    private javax.swing.JPanel jfamilyOptionsScreenBackground;
    private javax.swing.JPanel jnewFamilyPanel;
    // End of variables declaration//GEN-END:variables
}
