package familymanagersystem.forms;

/**
 *
 * @author Dário Silva & Délcio Morais
 * @since 2023
 * @version 1.0
 */
public class FamilyManager extends javax.swing.JFrame {
    /**
     * Creates new form FamilyManager
     */
    //screen moviments attributes
    int yMouse;
    int xMouse;

    public FamilyManager() {
        initComponents();
        new SystemDashBoard().dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jBackground = new javax.swing.JPanel();
        jSystemLogo = new javax.swing.JLabel();
        jRegistratePanel1 = new javax.swing.JPanel();
        jRegisterCompanyTitle1 = new javax.swing.JLabel();
        jCompanyIcon = new javax.swing.JLabel();
        jRegistratePanel2 = new javax.swing.JPanel();
        jAdminIcon = new javax.swing.JLabel();
        jAdminTitle = new javax.swing.JLabel();
        goToLoginButton = new javax.swing.JLabel();
        goToLoginText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home | Manage your Family");
        setBackground(new java.awt.Color(19, 19, 19));
        setLocation(new java.awt.Point(320, 90));
        setName("Home"); // NOI18N
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBackground.setBackground(new java.awt.Color(19, 19, 19));

        jSystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system_logo.png"))); // NOI18N

        jRegistratePanel1.setBackground(new java.awt.Color(45, 45, 45));
        jRegistratePanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(110, 86, 219)));
        jRegistratePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jRegisterCompanyTitle1.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        jRegisterCompanyTitle1.setForeground(new java.awt.Color(255, 255, 255));
        jRegisterCompanyTitle1.setText("Register a Company");

        jCompanyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company_purple_icon.png"))); // NOI18N

        javax.swing.GroupLayout jRegistratePanel1Layout = new javax.swing.GroupLayout(jRegistratePanel1);
        jRegistratePanel1.setLayout(jRegistratePanel1Layout);
        jRegistratePanel1Layout.setHorizontalGroup(
            jRegistratePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistratePanel1Layout.createSequentialGroup()
                .addGroup(jRegistratePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegistratePanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jRegisterCompanyTitle1))
                    .addGroup(jRegistratePanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jCompanyIcon)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jRegistratePanel1Layout.setVerticalGroup(
            jRegistratePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistratePanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jCompanyIcon)
                .addGap(18, 18, 18)
                .addComponent(jRegisterCompanyTitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRegistratePanel2.setBackground(new java.awt.Color(45, 45, 45));
        jRegistratePanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(110, 86, 219)));
        jRegistratePanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRegistratePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegistratePanel2MouseClicked(evt);
            }
        });

        jAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_logo.png"))); // NOI18N

        jAdminTitle.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        jAdminTitle.setForeground(new java.awt.Color(255, 255, 255));
        jAdminTitle.setText("Admin Area");

        javax.swing.GroupLayout jRegistratePanel2Layout = new javax.swing.GroupLayout(jRegistratePanel2);
        jRegistratePanel2.setLayout(jRegistratePanel2Layout);
        jRegistratePanel2Layout.setHorizontalGroup(
            jRegistratePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistratePanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jAdminTitle)
                .addGap(58, 58, 58))
            .addGroup(jRegistratePanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jAdminIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jRegistratePanel2Layout.setVerticalGroup(
            jRegistratePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistratePanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jAdminIcon)
                .addGap(18, 18, 18)
                .addComponent(jAdminTitle)
                .addContainerGap())
        );

        goToLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_icon.png"))); // NOI18N

        goToLoginText.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        goToLoginText.setForeground(new java.awt.Color(255, 255, 255));
        goToLoginText.setText("Go To Login");
        goToLoginText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToLoginText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToLoginTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jBackgroundLayout = new javax.swing.GroupLayout(jBackground);
        jBackground.setLayout(jBackgroundLayout);
        jBackgroundLayout.setHorizontalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackgroundLayout.createSequentialGroup()
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBackgroundLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jRegistratePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jRegistratePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBackgroundLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jSystemLogo)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(goToLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goToLoginText)
                .addGap(124, 124, 124))
        );
        jBackgroundLayout.setVerticalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSystemLogo)
                .addGap(57, 57, 57)
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRegistratePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegistratePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goToLoginButton)
                    .addComponent(goToLoginText))
                .addGap(50, 50, 50))
        );

        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        getAccessibleContext().setAccessibleName("Home");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // allows the user to moviment the form when dragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // gets the X and Y from the Screen
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jRegistratePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistratePanel2MouseClicked
        //closes the current window
        dispose();
        //opens the admin login form
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_jRegistratePanel2MouseClicked

    private void goToLoginTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLoginTextMouseClicked
        // goes to login screen
        dispose();
        new LoginAndRegistration().setVisible(true);
    }//GEN-LAST:event_goToLoginTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyManager().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goToLoginButton;
    private javax.swing.JLabel goToLoginText;
    private javax.swing.JLabel jAdminIcon;
    private javax.swing.JLabel jAdminTitle;
    private javax.swing.JPanel jBackground;
    private javax.swing.JLabel jCompanyIcon;
    private javax.swing.JLabel jRegisterCompanyTitle1;
    private javax.swing.JPanel jRegistratePanel1;
    private javax.swing.JPanel jRegistratePanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSystemLogo;
    // End of variables declaration//GEN-END:variables
}
