package familymanagersystem.forms;

import familymanagersystem.Pai;
import static familymanagersystem.forms.SystemDashBoard.familyToRegister;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dário Silva
 * @since 2023
 * @version 1.0
 */
public class FatherRegistration extends javax.swing.JFrame {

    //variables for the screen
    int xMouse;
    int yMouse;

    /**
     * Creates new form FatherRegistration
     */
    public FatherRegistration() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new components.RoundedPanel();
        roundedPanel2 = new components.RoundedPanel();
        jFatherRegistrationTitle = new javax.swing.JLabel();
        jFatherNameField = new javax.swing.JTextField();
        jCloseButton = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jGoBackButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBornDateField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register a Father");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 90));
        setName("Register a new Father"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));

        roundedPanel2.setBackground(new java.awt.Color(52, 61, 89));

        jFatherRegistrationTitle.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jFatherRegistrationTitle.setForeground(new java.awt.Color(255, 255, 255));
        jFatherRegistrationTitle.setText("Father Registration");

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jFatherRegistrationTitle)
                .addGap(93, 93, 93))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFatherRegistrationTitle)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jFatherNameField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jFatherNameField.setForeground(new java.awt.Color(52, 61, 89));
        jFatherNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFatherNameField.setToolTipText("Introduce the name");
        jFatherNameField.setAutoscrolls(false);
        jFatherNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(52, 61, 89)));
        jFatherNameField.setCaretColor(new java.awt.Color(102, 102, 102));
        jFatherNameField.setMargin(new java.awt.Insets(2, 5, 2, 2));

        jCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_icon.png"))); // NOI18N
        jCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseButtonMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(242, 239, 186));
        jButton1.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(52, 61, 89));
        jButton1.setText("Complete Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jGoBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go_back_icon.png"))); // NOI18N
        jGoBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jGoBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGoBackButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 61, 89));
        jLabel1.setLabelFor(jFatherNameField);
        jLabel1.setText("Name");

        jBornDateField.setForeground(new java.awt.Color(52, 61, 89));
        jBornDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jBornDateField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jBornDateField.setToolTipText("Introduce the born date");
        jBornDateField.setAutoscrolls(false);
        jBornDateField.setCaretColor(new java.awt.Color(102, 102, 102));
        jBornDateField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBornDateField.setMargin(new java.awt.Insets(2, 4, 2, 2));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 61, 89));
        jLabel2.setLabelFor(jFatherNameField);
        jLabel2.setText("Born Date");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jGoBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCloseButton)
                        .addGap(18, 18, 18))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFatherNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBornDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGoBackButton))
                .addGap(18, 18, 18)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jFatherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBornDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // allows the user to moviment the form when dragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // gets the X and Y from the Screen
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseButtonMouseClicked
        // exits the system
        System.exit(0);
    }//GEN-LAST:event_jCloseButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Registrates a new Father to the Family
        String fatherName = jFatherNameField.getText();
        String bornDate = jBornDateField.getText();

        //tests if both field are empty
        if (fatherName.isBlank() && bornDate.isBlank()) {
            JOptionPane.showMessageDialog(null, "You Need To Fill All The Fields", "Please, Fill Out All Fields", 0);
        } else {
            //tests if a field is empty
            if (fatherName.isBlank() || bornDate.isBlank()) {
                JOptionPane.showMessageDialog(null, "You Need To Fill All The Fields", "Please, Fill Out All Fields", 0);
            } else {
                //holds all information related to the father
                File fatherInformation = new File(RegistrationMainScreen.defaultFamilyFilePath + "\\" + familyToRegister + "\\father.txt");

                //checks if there's already a registered father
                if (fatherInformation.exists()) {
                    //shows an error message
                    JOptionPane.showMessageDialog(null, "<html>This Family Already Has Father</html>", "Registration Failed", 1);
                } else {

                    //creates the file inside the given family folder
                    try {
                        if (fatherInformation.createNewFile()) {

                            //creates a writer for the file
                            FileWriter fatherInformationFileWriter = new FileWriter(fatherInformation);

                            //setts all values to the father class
                            Pai.setBornDate(bornDate);
                            Pai.setGender("Male");
                            Pai.setName(fatherName);

                            //writes all info in the file
                            fatherInformationFileWriter.write("Name:" + Pai.getName() + "\n");
                            fatherInformationFileWriter.write("Gender:" + Pai.getGender() + "\n");
                            fatherInformationFileWriter.write("Born Date:" + Pai.getBornDate() + "\n");

                            //closes the writer object
                            fatherInformationFileWriter.close();

                            //shows a success message
                            JOptionPane.showMessageDialog(null, "<html>The Father Was Successfully Registered !</html>", "Registration Complete", 2);
                        }
                    } catch (IOException e) {
                        //shows an error message
                        JOptionPane.showMessageDialog(null, "<html>There's been a error while <br> <strong>trying to save the info</strong> about<br>the father</html>", "Registration Failed", 1);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jGoBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGoBackButtonMouseClicked
        // returns to the SystemDasBoard Form

        //closes the current window
        dispose();

        //opens the System Dasboard Form
        new SystemDashBoard().setVisible(true);
    }//GEN-LAST:event_jGoBackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FatherRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FatherRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FatherRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FatherRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FatherRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jBornDateField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCloseButton;
    private javax.swing.JTextField jFatherNameField;
    private javax.swing.JLabel jFatherRegistrationTitle;
    private javax.swing.JLabel jGoBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private components.RoundedPanel roundedPanel1;
    private components.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
