package familymanagersystem.forms;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dário Silva & Délcio Morais
 * @since 2023
 * @version 1.0
 */
public class RegistrationMainScreenOptionsScreen extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationMainScreenOptionsScreen
     */
    public RegistrationMainScreenOptionsScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFatherOptionPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFatherOptionPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFatherOptionPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFatherOptionPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jregistrationMainScreenOptionsBackground = new javax.swing.JPanel();
        jCloseBackground = new javax.swing.JPanel();
        jCloseIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(19, 19, 19));
        setPreferredSize(new java.awt.Dimension(450, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFatherOptionPanel.setBackground(new java.awt.Color(45, 45, 45));
        jFatherOptionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(110, 86, 219)));
        jFatherOptionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register A Mother");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jFatherOptionPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 33, -1, -1));

        add(jFatherOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 360, 90));

        jFatherOptionPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jFatherOptionPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(110, 86, 219)));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register A Father");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFatherOptionPanel1Layout = new javax.swing.GroupLayout(jFatherOptionPanel1);
        jFatherOptionPanel1.setLayout(jFatherOptionPanel1Layout);
        jFatherOptionPanel1Layout.setHorizontalGroup(
            jFatherOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFatherOptionPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jFatherOptionPanel1Layout.setVerticalGroup(
            jFatherOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFatherOptionPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(jFatherOptionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 360, 90));

        jFatherOptionPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jFatherOptionPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(110, 86, 219)));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Register A Daughter");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jFatherOptionPanel2Layout = new javax.swing.GroupLayout(jFatherOptionPanel2);
        jFatherOptionPanel2.setLayout(jFatherOptionPanel2Layout);
        jFatherOptionPanel2Layout.setHorizontalGroup(
            jFatherOptionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFatherOptionPanel2Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(92, 92, 92))
        );
        jFatherOptionPanel2Layout.setVerticalGroup(
            jFatherOptionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFatherOptionPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );

        add(jFatherOptionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 360, 90));

        jFatherOptionPanel3.setBackground(new java.awt.Color(45, 45, 45));
        jFatherOptionPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(110, 86, 219)));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Register A Son");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFatherOptionPanel3Layout = new javax.swing.GroupLayout(jFatherOptionPanel3);
        jFatherOptionPanel3.setLayout(jFatherOptionPanel3Layout);
        jFatherOptionPanel3Layout.setHorizontalGroup(
            jFatherOptionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFatherOptionPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel4)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jFatherOptionPanel3Layout.setVerticalGroup(
            jFatherOptionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFatherOptionPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(25, 25, 25))
        );

        add(jFatherOptionPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 360, 90));

        jregistrationMainScreenOptionsBackground.setBackground(new java.awt.Color(19, 19, 19));

        jCloseBackground.setBackground(new java.awt.Color(36, 36, 36));
        jCloseBackground.setForeground(new java.awt.Color(90, 105, 154));

        jCloseIcon.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jCloseIcon.setForeground(new java.awt.Color(255, 255, 255));
        jCloseIcon.setText("  X");
        jCloseIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCloseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jCloseBackgroundLayout = new javax.swing.GroupLayout(jCloseBackground);
        jCloseBackground.setLayout(jCloseBackgroundLayout);
        jCloseBackgroundLayout.setHorizontalGroup(
            jCloseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCloseBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCloseIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        jCloseBackgroundLayout.setVerticalGroup(
            jCloseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCloseBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCloseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jregistrationMainScreenOptionsBackgroundLayout = new javax.swing.GroupLayout(jregistrationMainScreenOptionsBackground);
        jregistrationMainScreenOptionsBackground.setLayout(jregistrationMainScreenOptionsBackgroundLayout);
        jregistrationMainScreenOptionsBackgroundLayout.setHorizontalGroup(
            jregistrationMainScreenOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jregistrationMainScreenOptionsBackgroundLayout.createSequentialGroup()
                .addGap(0, 390, Short.MAX_VALUE)
                .addComponent(jCloseBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jregistrationMainScreenOptionsBackgroundLayout.setVerticalGroup(
            jregistrationMainScreenOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jregistrationMainScreenOptionsBackgroundLayout.createSequentialGroup()
                .addComponent(jCloseBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 521, Short.MAX_VALUE))
        );

        add(jregistrationMainScreenOptionsBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void jCloseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseIconMouseClicked
        //checks if the user already registered a father or a mother
        // closing the window
        System.exit(0);
    }//GEN-LAST:event_jCloseIconMouseClicked

    private void showPanel(JPanel p) {
        p.setSize(450, 550);
        p.setLocation(0, 0);

        jregistrationMainScreenOptionsBackground.removeAll();
        jregistrationMainScreenOptionsBackground.add(p, BorderLayout.CENTER);
        jregistrationMainScreenOptionsBackground.revalidate();
        jregistrationMainScreenOptionsBackground.repaint();

    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // opens the father registration screen
        RegistrationMainScreenFatherRegistration FatherScreen = new RegistrationMainScreenFatherRegistration();
        showPanel(FatherScreen);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // opens the mother registration screen
        RegistrationMainScreenMotherRegistration MotherScreen = new RegistrationMainScreenMotherRegistration();
        showPanel(MotherScreen);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // opens the son registration screen
        RegistrationMainScreenSonRegistration SonScreen = new RegistrationMainScreenSonRegistration();
        showPanel(SonScreen);
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jCloseBackground;
    private javax.swing.JLabel jCloseIcon;
    private javax.swing.JPanel jFatherOptionPanel;
    private javax.swing.JPanel jFatherOptionPanel1;
    private javax.swing.JPanel jFatherOptionPanel2;
    private javax.swing.JPanel jFatherOptionPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jregistrationMainScreenOptionsBackground;
    // End of variables declaration//GEN-END:variables
}
